name: Build env
description: Sets up Java and Gradle
runs:
  using: composite
  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v5
